window.HENRI_NANCY_WEDDING_BACKUP = {
  "version": 3,
  "exportedAt": "2026-08-25T19:26:52.996Z",
  "details": {
    "auto-main1-section1-div2-p1-text1": "Wedding squad field guide",
    "groom-name": "Nancy",
    "auto-main1-section1-div2-h11-i1-text1": "&",
    "bride-name": "Henri",
    "wedding-date-display": "Saturday · 19 September 2026 · Suomenlinna",
    "auto-main1-section1-div2-div1-span1-b1-text1": "15:00",
    "auto-main1-section1-div2-div1-span1-text1": "Ceremony",
    "auto-main1-section1-div2-div1-span2-b1-text1": "01:00",
    "auto-main1-section1-div2-div1-span2-text1": "Venue clear",
    "auto-main1-section2-div1-div1-p1-text1": "At a glance",
    "auto-main1-section2-div1-div1-h21-text1": "The day, in one breath",
    "auto-main1-section2-div1-p1-text1": "A calm and hopefully rain free island morning, at 15:00 ceremony starts at Suomenlinna Church, then dinner and dancing under the brick vaults of Tenalji von Fersen.",
    "auto-main1-section2-div2-article1-span1-text1": "01",
    "auto-main1-section2-div2-article1-p1-text1": "Ceremony",
    "auto-main1-section2-div2-article1-h31-text1": "Suomenlinna Church",
    "auto-main1-section2-div2-article1-p2-text1": "Guest welcome from 14:45. Everyone in position by 14:55. Ceremony starts at 15:00 sharp.",
    "auto-main1-section2-div2-article2-span1-text1": "02",
    "auto-main1-section2-div2-article2-p1-text1": "Reception",
    "auto-main1-section2-div2-article2-h31-text1": "Tenalji von Fersen",
    "auto-main1-section2-div2-article2-p2-text1": "Guest portraits and drinks from 16:15, dinner and speeches from 16:45, first dance at 20:45. The venue must be empty by 01:00.",
    "auto-main1-section2-div2-article3-span1-text1": "03",
    "auto-main1-section2-div2-article3-p1-text1": "Squad rule",
    "auto-main1-section2-div2-article3-h31-text1": "Don't forget to have fun",
    "auto-main1-section2-div2-article3-p2-text1": "Help when needed but don't stress over the small stuffs. We want you to enjoy the day just as much as we do.",
    "auto-main1-section2-aside1-span1-text1": "!",
    "auto-main1-section2-aside1-div1-strong1-text1": "Draft assumptions to confirm",
    "assumptions": "Hotel and venue-access details are still TBD. Ceremony finish is estimated between 15:30 and 15:40. Reconfirm the 12:10 ferry and last return ferry, supplier arrivals, speech slots, wedding-car plan, closing procedure and after-party location.",
    "auto-main1-section3-div1-div1-div1-p1-text1": "Run of show",
    "auto-main1-section3-div1-div1-div1-h21-text1": "Wedding-day timeline",
    "auto-main1-section3-div1-div1-p1-text1": "",
    "auto-main1-section3-div1-div2-div1-span1-text1": "Hotel morning",
    "auto-main1-section3-div1-div2-div1-small1-text1": "Eat · prepare · photograph",
    "t-0830": "08:30",
    "t-0830-title": "Breakfast and getting ready",
    "t-0830-copy": "Bride party at hotel getting ready, groom and best men: steam every outfits. Eat a proper breakfast and drink plenty of water. It is a long day — please do not get drunk before the ceremony ;)",
    "auto-main1-section3-div1-div2-article1-div2-span1-text1": "",
    "t-1100": "11:00",
    "t-1100-title": "Bride and squad portraits",
    "t-1100-copy": "Bride and bridesmaids take portraits together in the hotel room. Keep the room tidy and all personal items gathered in one area.",
    "auto-main1-section3-div1-div2-article2-div2-span1-text1": "",
    "t-1130": "11:30",
    "t-1130-title": "First look at the hotel",
    "t-1130-copy": "Clear the space, keep the moment private and make sure the photographer and videographer are ready before bringing Henri into the room.",
    "auto-main1-section3-div1-div2-article3-div2-span1-text1": "",
    "t-1145": "11:45",
    "t-1145-title": "Final supplier check and leave the hotel",
    "t-1145-copy": "Confirm suppliers, charge phones, pack personal bags and complete the checklist before anyone leaves the hotel. Rings, vows, bouquets, programmes and emergency kits must be accounted for.",
    "auto-main1-section3-div1-div2-article4-div2-span1-text1": "",
    "t-1210": "12:10",
    "t-1210-title": "Ferry to Suomenlinna reconfirm schedule",
    "t-1210-copy": "Travel together on the planned 12:10 ferry. Arrive at the pier early enough to board calmly with all bags, outfits, bouquets and photo equipment.",
    "auto-main1-section3-div1-div2-article5-div2-span1-text1": "",
    "t-1230-1415": "12:30–14:15",
    "t-1230-1415-title": "Couple and squad portraits on Suomenlinna",
    "t-1230-1415-copy": "Photograph the couple and full wedding squad around the island. Sylvia keeps the touch-up kit and warm layer close; Juha keeps the rings secure at all times.",
    "auto-main1-section3-div1-div2-article6-div2-span1-text1": "",
    "auto-main1-section3-div1-div2-div2-span1-text1": "Ceremony",
    "auto-main1-section3-div1-div2-div2-small1-text1": "Arrive · welcome · marry",
    "t-1415": "14:15",
    "t-1415-title": "Start heading to the church",
    "t-1415-copy": "Finish the island portraits, gather every personal item and move the couple and squad toward Suomenlinna Church without rushing.",
    "auto-main1-section3-div1-div2-article7-div2-span1-text1": "",
    "t-1430": "14:30",
    "t-1430-title": "Bride to the bridal chamber",
    "t-1430-copy": "Nancy moves into the bridal chamber and stays hidden from arriving guests. Bridesmaids protect the route and keep the room calm.",
    "auto-main1-section3-div1-div2-article8-div2-span1-text1": "",
    "t-1445": "14:40",
    "t-1445-title": "Guest welcome begins",
    "t-1445-copy": "Two squad members greet guests at the church entrance and hand out ceremony programmes. Another two squad members guide guests inside the church for seating.",
    "auto-main1-section3-div1-div2-article9-div2-span1-text1": "",
    "t-1455": "14:55",
    "t-1455-title": "Final positions and checks",
    "t-1455-copy": "Everyone in position. Phones away, rings checked and bouquets checked. Henri, bestmen and bridemaids are ready to move to their position; Sylvia checks Nancy’s veil and dress one last time.",
    "auto-main1-section3-div1-div2-article10-div2-span1-text1": "",
    "t-1500": "15:00",
    "t-1500-title": "Ceremony starts",
    "t-1500-copy": "Henri and Nancy get married at Suomenlinna Church. The squad stays present, discreet and ready to help.",
    "auto-main1-section3-div1-div2-article11-div2-span1-text1": "",
    "t-1530-1540": "15:30–15:40",
    "t-1530-1540-title": "Estimated finish, congratulations and group photo",
    "t-1530-1540-copy": "After the ceremony, coordinate every guest for one full group photo at the church entrance. Keep the entrance clear and help the photographer gather everyone quickly.",
    "auto-main1-section3-div1-div2-article12-div2-span1-text1": "",
    "t-1550": "15:50",
    "t-1550-title": "Wedding car ready; guide guests to the venue",
    "t-1550-copy": "Confirm the wedding car, then guide guests to Tenalji von Fersen. Explain also that each guest will take a photo with the couple at reception before collecting a welcome drink. Use the easier route with fewer cobblestones for elderly guests and anyone needing support.",
    "auto-main1-section3-div1-div2-article13-div2-span1-text1": "",
    "auto-main1-section3-div1-div2-div3-span1-text1": "Reception",
    "auto-main1-section3-div1-div2-div3-small1-text1": "Photograph · dine · play · dance",
    "t-1615": "16:15",
    "t-1615-title": "Guest portraits and welcome drinks",
    "t-1615-copy": "Every guest takes a photo with Henri and Nancy first, then collects a welcome drink. Squad members manage the queue, coats, cards and guest flow.",
    "auto-main1-section3-div1-div2-article14-div2-span1-text1": "",
    "t-1630": "16:30",
    "t-1630-title": "Guests begin finding their seats",
    "t-1630-copy": "Gently move guests toward their tables and help with the seating plan, mobility needs and children as required.",
    "auto-main1-section3-div1-div2-article15-div2-span1-text1": "",
    "t-1645-welcome": "16:45",
    "t-1645-welcome-title": "Welcome speech and menu introduction",
    "t-1645-welcome-copy": "The Master of Ceremonies welcomes everyone and the head of catering introduces the day’s menu and any practical service details.",
    "auto-main1-section3-div1-div2-article16-div2-span1-text1": "",
    "t-1645-1900": "16:45–19:00",
    "t-1645-1900-title": "Dinner and surprise speeches",
    "t-1645-1900-copy": "Dinner is served with speeches between agreed courses. Anyone who wants to speak that I do not know about should DM Nancy privately — Henri wants the speeches to remain a surprise. Nancy will reserve every requested slot and pass the final order to the MC.",
    "auto-main1-section3-div1-div2-article17-div2-span1-text1": "",
    "t-1900": "19:00",
    "t-1900-title": "Programme and games  (Henrik & Liam) — the shoe game and something else ?",
    "t-1900-copy": "Set the couple’s chairs back-to-back, prepare both pairs of shoes and have the questions ready. Keep the game warm, fun and well paced. More activities to be added likely in coming days.",
    "auto-main1-section3-div1-div2-article18-div2-span1-text1": "",
    "t-2000-2030": "20:00–20:30",
    "t-2000-2030-title": "Dessert, cake and coffee",
    "t-2000-2030-copy": "Coordinate the cake moment, coffee service and photos. MC quietly confirms the first-dance music and lighting.",
    "auto-main1-section3-div1-div2-article19-div2-span1-text1": "",
    "t-2045": "20:45",
    "t-2045-title": "First dance",
    "t-2045-copy": "Cue the first-dance music and clear the floor. After the couple’s dance, invite the wedding party and guests to join.",
    "auto-main1-section3-div1-div2-article20-div2-span1-text1": "",
    "t-2200": "22:00",
    "t-2200-title": "Late-night snacks",
    "t-2200-copy": "Announce the food, make sure the couple receives a plate and check that dietary alternatives are clearly identified.",
    "auto-main1-section3-div1-div2-article21-div2-span1-text1": "",
    "t-2230": "22:15",
    "t-2230-title": "Music bingo",
    "t-2230-copy": "Hand out bingo cards and pens, explain the rules and coordinate the music with the DJ or band. Have the prizes ready before starting.",
    "auto-main1-section3-div1-div2-article22-div2-span1-text1": "",
    "auto-main1-section3-div1-div2-div4-span1-text1": "Close & travel",
    "auto-main1-section3-div1-div2-div4-small1-text1": "Lower · pack · leave quietly",
    "t-0000": "00:00",
    "t-0000-title": "Music quieter, last call and packing begins",
    "t-0000-copy": "Lower the music, announce last call and start packing items that can leave without disrupting the final half-hour. Secure cards, gifts and personal belongings first.",
    "auto-main1-section3-div1-div2-article23-div2-span1-text1": "",
    "t-0030": "00:30",
    "t-0030-title": "Music ends; guests head to the pier",
    "t-0030-copy": "Keep voices and music low outside and respect Suomenlinna’s residential area. Squad members begin the final venue sweep.",
    "auto-main1-section3-div1-div2-article24-div2-span1-text1": "",
    "t-0100": "01:00",
    "t-0100-title": "Venue empty and locked",
    "t-0100-copy": "Everyone must be out - as well as everything required by the rental agreement? Check toilets, cloakroom, kitchen, stage, windows, waste points and access procedure. No exceptions.",
    "auto-main1-section3-div1-div2-article25-div2-span1-text1": "",
    "t-0200": "02:00",
    "t-0200-title": "Last ferry",
    "t-0200-copy": "Do not miss the final planned departure. After-party location is still open — let us know if you want to continue and have a suggestion for where everyone should go.",
    "auto-main1-section3-div1-div2-article26-div2-span1-text1": "",
    "auto-main1-section4-div1-div1-p1-text1": "People",
    "auto-main1-section4-div1-div1-h21-text1": "The wedding squad",
    "auto-main1-section4-div1-p1-text1": "",
    "auto-main1-section4-div2-article1-p1-text1": "Bride",
    "couple-bride-name": "Supphatra Mukdakul",
    "auto-main1-section4-div2-article1-span1-text1": "aka Nancy",
    "auto-main1-section4-div2-article2-p1-text1": "Groom",
    "couple-groom-name": "Henri Ailio",
    "auto-main1-section4-div3-article1-div2-p1-text1": "Maid of Honor - emergency hotline",
    "moh-name": "Sylvia Rizanova",
    "moh-contact": "+359 88 420 3688 · English only",
    "moh-duty-1": "Nancy’s calm, timing and personal items",
    "moh-duty-2": "Bouquet, veil, dress and touch-up kit",
    "moh-duty-3": "Main link to photographer and ceremony lead",
    "moh-duty-4": "Sunset wrap and couple’s overnight bag",
    "auto-main1-section4-div3-article2-div2-p1-text1": "Bridesmaid - guest coordination",
    "bm2-name": "Liam July",
    "bm2-contact": "+358 45 643 0850",
    "bridesmaid-coordination-duty-1": "Décor, stationery and detail checklist",
    "bridesmaid-coordination-duty-2": "Guest welcome and mobility support",
    "bridesmaid-coordination-duty-3": "Guest coordination in the church",
    "bridesmaid-coordination-duty-4": "Game coordinator",
    "auto-main1-section4-div3-article3-div2-p1-text1": "Bridesmaid - guest welcome",
    "bm3-name": "Rashida Arvonen",
    "bm3-contact": "+358 40 667 3788 · English only",
    "bridesmaid-welcome-duty-1": "Décor, stationery and detail checklist",
    "bridesmaid-welcome-duty-2": "Guest welcome and mobility support",
    "bridesmaid-welcome-duty-3": "Group-photo wrangling",
    "bridesmaid-welcome-duty-4": "Cards, gifts and keepsakes",
    "auto-main1-section4-div3-article4-div2-p1-text1": "Best Man · MC",
    "best1-name": "Khalil Shahramian",
    "best1-contact": "+358 40 142 4041",
    "bestman-mc-duty-1": "Master of ceremonies and programme timing",
    "bestman-mc-duty-2": "Coordinate surprise speeches privately with Nancy",
    "bestman-mc-duty-3": "AV, microphones and music cues",
    "bestman-mc-duty-4": "Lead final guest departure at 00:30",
    "auto-main1-section4-div3-article5-div2-p1-text1": "Best Man - rings",
    "best2-name": "Juha Kvist",
    "best2-contact": "+358 50 371 1410",
    "bestman-rings-duty-1": "Henri's timing and outfit",
    "bestman-rings-duty-2": "Physical custody of both rings",
    "bestman-rings-duty-3": "Guest coordination in the church",
    "auto-main1-section4-div3-article6-div2-p1-text1": "Best Man - guest welcome",
    "best3-name": "Henrik Arvonen",
    "best3-contact": "+358 44 534 6120",
    "bestman-welcome-duty-1": "Guest welcome and mobility support",
    "bestman-welcome-duty-2": "Group-photo wrangling",
    "bestman-welcome-duty-3": "Game coordinator",
    "auto-main1-section5-div1-div1-div1-p1-text1": "What to wear",
    "auto-main1-section5-div1-div1-div1-h21-text1": "A coordinated wedding squad",
    "auto-main1-section5-div1-div1-p1-text1": "The palette is classic black and white, brought together with warm brown details that connect the best men and bridesmaids.",
    "auto-main1-section5-div1-div2-span1-text1": "Black",
    "auto-main1-section5-div1-div2-span2-text1": "White",
    "auto-main1-section5-div1-div2-span3-text1": "Warm brown",
    "auto-main1-section5-div1-div3-article1-p1-text1": "Best men · coordinated formalwear",
    "auto-main1-section5-div1-div3-article1-h31-text1": "Black suit, white shirt,",
    "auto-main1-section5-div1-div3-article1-h31-text3": "brown details",
    "bestmen-dress-intro": "It would be wonderful if all three best men could match in black suits with crisp white shirts.",
    "auto-main1-section5-div1-div3-article1-ul1-li1-span1-text1": "01",
    "auto-main1-section5-div1-div3-article1-ul1-li1-div1-strong1-text1": "Suit",
    "bestmen-suit": "Black suit, neatly fitted and pressed",
    "auto-main1-section5-div1-div3-article1-ul1-li2-span1-text1": "02",
    "auto-main1-section5-div1-div3-article1-ul1-li2-div1-strong1-text1": "Shirt",
    "bestmen-shirt": "Crisp white dress shirt",
    "auto-main1-section5-div1-div3-article1-ul1-li3-span1-text1": "03",
    "auto-main1-section5-div1-div3-article1-ul1-li3-div1-strong1-text1": "Accessories",
    "bestmen-accessories": "Brown bow tie and matching brown pocket square (handkerchief)",
    "auto-main1-section5-div1-div3-article1-aside1-strong1-text1": "Need the brown accessories?",
    "bestmen-accessory-help": "If you do not have a brown bow tie or pocket square in the right color, please let us know — we will help provide them.",
    "auto-main1-section5-div1-div3-article2-p1-text1": "Bridesmaids · warm brown palette",
    "auto-main1-section5-div1-div3-article2-h31-text1": "Brown dresses,",
    "auto-main1-section5-div1-div3-article2-h31-text3": "beautifully coordinated",
    "bridesmaids-dress-intro": "All three bridesmaids, including the Maid of Honor, will wear brown to connect with the best men’s accessories.",
    "auto-main1-section5-div1-div3-article2-ul1-li1-span1-text1": "01",
    "auto-main1-section5-div1-div3-article2-ul1-li1-div1-strong1-text1": "Dress color",
    "bridesmaids-color": "Warm brown in the agreed wedding-party shade",
    "auto-main1-section5-div1-div3-article2-ul1-li2-span1-text1": "02",
    "auto-main1-section5-div1-div3-article2-ul1-li2-div1-strong1-text1": "Coordination",
    "bridesmaids-coordination": "Please coordinate the final shade and styling together before purchasing",
    "auto-main1-section5-div1-div3-article2-ul1-li3-span1-text1": "03",
    "auto-main1-section5-div1-div3-article2-ul1-li3-div1-strong1-text1": "Island comfort",
    "bridesmaids-comfort": "Bring a warm layer and comfortable backup shoes for Suomenlinna’s outdoor paths and cobblestones",
    "auto-main1-section5-div1-div3-article2-aside1-strong1-text1": "Not sure about the shade?",
    "bridesmaids-shade-help": "Send a photo to Nancy or Sylvia before buying so the brown tones feel cohesive together.",
    "auto-main1-section6-div1-div1-div1-p1-text1": "Creative & service team",
    "auto-main1-section6-div1-div1-div1-h21-text1": "Vendor information",
    "auto-main1-section6-div1-div1-p1-text1": "Keep the people, numbers, arrival times and important cues in one place.",
    "auto-main1-section6-div1-div2-article1-div1-text1": "01",
    "auto-main1-section6-div1-div2-article1-p1-text1": "Photography & film",
    "auto-main1-section6-div1-div2-article1-h31-text1": "Capture the story",
    "auto-main1-section6-div1-div2-article1-div2-section1-p1-text1": "Photographer",
    "photographer-name": "Maksim Didyk",
    "photographer-contact": "+358 46 433 1098",
    "photographer-hours": "Approximately 10 hours",
    "auto-main1-section6-div1-div2-article1-div2-section1-div1-small1-text1": "Wedding-day coverage",
    "auto-main1-section6-div1-div2-article1-div2-section2-p1-text1": "Videographer",
    "videographer-name": "Joona Saaresto",
    "videographer-contact": "+358 40 777 0635",
    "videographer-hours": "Approximately 8 hours",
    "auto-main1-section6-div1-div2-article1-div2-section2-div1-small1-text1": "Wedding-day coverage",
    "auto-main1-section6-div1-div2-article1-p2-text1": "Important moments",
    "photo-video-cues": "Hotel portraits 11:00 · first look 11:30 · island portraits 12:30–14:15 · ceremony and full group photo · guest portraits 16:15 · speeches · cake · first dance 20:45",
    "auto-main1-section6-div1-div2-article2-div1-text1": "02",
    "auto-main1-section6-div1-div2-article2-p1-text1": "DJ & sound",
    "auto-main1-section6-div1-div2-article2-h31-text1": "Hold the rhythm",
    "auto-main1-section6-div1-div2-article2-div2-div1-span1-text1": "DJ / company",
    "dj-name": "DJ palvelut / Valtteri Keskitalo",
    "auto-main1-section6-div1-div2-article2-div2-div2-span1-text1": "Contact",
    "dj-contact": "+358 40 023 7022 / djcenterhouse@gmail.com",
    "auto-main1-section6-div1-div2-article2-div2-div3-span1-text1": "Arrival / setup",
    "dj-arrival": "16:30 ?",
    "auto-main1-section6-div1-div2-article2-div2-div4-span1-text1": "Sound check",
    "dj-soundcheck": "17:30 ?",
    "auto-main1-section6-div1-div2-article2-p2-text1": "Music cues",
    "dj-cues": "Welcome and speech microphones 16:45 · shoe game 19:00 · cake music 20:00–20:30 · first dance 20:45 · music bingo 22:30 · quieter music from 00:00 · music ends 00:30",
    "auto-main1-section6-div1-div2-article3-div1-text1": "03",
    "auto-main1-section6-div1-div2-article3-p1-text1": "Live band",
    "auto-main1-section6-div1-div2-article3-h31-text1": "Bring the room alive",
    "auto-main1-section6-div1-div2-article3-div2-div1-span1-text1": "Band",
    "band-name": "Rami",
    "auto-main1-section6-div1-div2-article3-div2-div2-span1-text1": "Contact",
    "band-contact": "+358 45 6973 089",
    "auto-main1-section6-div1-div2-article3-div2-div3-span1-text1": "Arrival / load-in",
    "band-arrival": "18.09.2026 evening",
    "auto-main1-section6-div1-div2-article3-div2-div4-span1-text1": "Sound check",
    "band-soundcheck": "18.09.2026",
    "auto-main1-section6-div1-div2-article3-p2-text1": "Performance plan",
    "band-plan": "Number and length of sets TBD · break music coordinated with DJ · final song and pack-down timing to confirm",
    "auto-main1-section6-div1-div2-article4-div1-text1": "04",
    "auto-main1-section6-div1-div2-article4-p1-text1": "Catering",
    "auto-main1-section6-div1-div2-article4-h31-text1": "Feed everyone beautifully",
    "auto-main1-section6-div1-div2-article4-div2-div1-span1-text1": "Company / lead",
    "catering-name": "Ahaan Tam Sang Forum (Warakorn)",
    "auto-main1-section6-div1-div2-article4-div2-div2-span1-text1": "Contact",
    "catering-contact": "+358 40 168 3331",
    "auto-main1-section6-div1-div2-article4-div2-div3-span1-text1": "Arrival / kitchen",
    "catering-arrival": "10:00",
    "auto-main1-section6-div1-div2-article4-div2-div4-span1-text1": "Final guest count",
    "catering-guest-count": "110 max",
    "auto-main1-section6-div1-div2-article4-p2-text1": "Service cues",
    "catering-cues": "Guest portraits and welcome drinks 16:15 · menu introduction and dinner 16:45 · speeches during dinner · cake and coffee 20:00–20:30 · late-night snacks 22:00 · dietary list attached",
    "auto-main1-section6-div1-aside1-div1-p1-text1": "Main vendor liaison",
    "vendor-liaison": "Liam July · +358 45 643 0850",
    "vendor-contact-rule": "On the wedding day, suppliers contact the vendor liaison first. Make sure catering, band/dj and everything is ready before guest flow into the venue.",
    "auto-main1-section6-div1-aside1-div2-div1-p1-text1": "Main decision maker",
    "day-decision-maker": "Sylvia Rizanova · +359 884 203 688",
    "day-decision-maker-rule": "Silviya keeps the overall day moving and makes the final call when the squad needs a quick answer. Bring timing changes, guest concerns and unexpected situations to her first; she will involve Nancy only when necessary.",
    "auto-main1-section9-div1-div1-p1-text1": "Places & passage",
    "auto-main1-section9-div1-div1-h21-text1": "Venue information",
    "auto-main1-section9-div1-p1-text1": "Use the official links for live schedules and final operating instructions. Ferry times should be rechecked shortly before the wedding.",
    "auto-main1-section9-div2-article1-div1-span1-text1": "01 · Ceremony",
    "auto-main1-section9-div2-article1-div1-span2-text1": "15:00",
    "auto-main1-section9-div2-article1-h31-text1": "Suomenlinna Church",
    "auto-main1-section9-div2-article1-address1-text1": "Suomenlinna C 43",
    "auto-main1-section9-div2-article1-address1-text3": "00190 Helsinki",
    "auto-main1-section9-div2-article1-dl1-div1-dt1-text1": "From main pier",
    "auto-main1-section9-div2-article1-dl1-div1-dd1-text1": "About 200 m",
    "auto-main1-section9-div2-article1-dl1-div2-dt1-text1": "Arrival target",
    "auto-main1-section9-div2-article1-dl1-div2-dd1-text1": "Guests by 14:30-14:45",
    "auto-main1-section9-div2-article1-dl1-div3-dt1-text1": "Terrain",
    "auto-main1-section9-div2-article1-dl1-div3-dd1-text1": "Outdoor island paths",
    "auto-main1-section9-div2-article1-p1-text1": "The landmark church tower also serves as a lighthouse. Keep the church entrance and processional route clear from 14:40.",
    "auto-main1-section9-div2-article2-div1-span1-text1": "02 · Reception",
    "auto-main1-section9-div2-article2-div1-span2-text1": "01:00 clear",
    "auto-main1-section9-div2-article2-h31-text1": "Tenalji von Fersen",
    "auto-main1-section9-div2-article2-address1-text1": "Suomenlinna B 17 C",
    "auto-main1-section9-div2-article2-address1-text3": "00190 Helsinki",
    "auto-main1-section9-div2-article2-dl1-div1-dt1-text1": "From main pier",
    "auto-main1-section9-div2-article2-dl1-div1-dd1-text1": "About 700 m",
    "auto-main1-section9-div2-article2-dl1-div2-dt1-text1": "Arrival target",
    "auto-main1-section9-div2-article2-dl1-div2-dd1-text1": "Guests by 16:15",
    "auto-main1-section9-div2-article2-dl1-div3-dt1-text1": "Access note",
    "auto-main1-section9-div2-article2-dl1-div3-dd1-text1": "Second-floor hall; lift by advance arrangement",
    "auto-main1-section9-div2-article2-p1-text1": "The 1775 former granary includes tables and chairs, stage, microphones, projector, screens, Bluetooth/HDMI and WLAN. Confirm the current equipment list and rental terms.",
    "auto-main1-section9-div2-article3-div1-span1-text1": "03 · Travel",
    "auto-main1-section9-div2-article3-div1-span2-text1": "Last ferry 02:00",
    "auto-main1-section9-div2-article3-h31-text1": "Market Square ferry",
    "auto-main1-section9-div2-article3-address1-text1": "Eastern side of Kauppatori",
    "auto-main1-section9-div2-article3-address1-text3": "near the Presidential Palace",
    "auto-main1-section9-div2-article3-dl1-div1-dt1-text1": "Crossing",
    "auto-main1-section9-div2-article3-dl1-div1-dd1-text1": "About 15 min",
    "auto-main1-section9-div2-article3-dl1-div2-dt1-text1": "HSL route",
    "auto-main1-section9-div2-article3-dl1-div2-dd1-text1": "Line 19 · AB ticket",
    "auto-main1-section9-div2-article3-dl1-div3-dt1-text1": "Island",
    "auto-main1-section9-div2-article3-dl1-div3-dd1-text1": "Car-free; cobblestones",
    "auto-main1-section9-div2-article3-p1-text1": "Tickets must be valid before entering the pier payment area. It's already winter timetable for the ferries so double check and do not miss the ferry.",
    "auto-main1-section9-div3-div1-span1-text1": "≈",
    "auto-main1-section9-div3-div1-h31-text1": "Island-weather plan",
    "weather-plan": "Have clear or dark umbrellas, warm wraps for the bride and bridesmaids, flat backup shoes, heel protectors, tissues and two dry towels. Please checks the forecast at 48 hours and again on the morning.",
    "auto-main1-section9-div4-article1-p1-text1": "Primary decision maker",
    "primary-contact": "Silviya Rizanova · +359 884 203 688",
    "auto-main1-section9-div4-article2-p1-text1": "Transport and guest help",
    "transport-contact": "Juha Kvist · +358 50 371 1410",
    "auto-main1-section9-div4-article3-p1-text1": "Venue / AV / closing",
    "venue-contact": "Henrik Arvonen · +358 44 534 6120",
    "auto-main1-section9-div4-article4-p1-text1": "Suomenlinna Event Facilities",
    "auto-main1-section9-div4-article4-h31-text1": "+358 29 533 6420",
    "auto-main1-section9-div4-article5-p1-text1": "Emergency",
    "auto-main1-section9-div4-article5-h31-text1": "112",
    "auto-main1-section9-div4-article5-span1-text1": "Give the building name and Suomenlinna address.",
    "auto-main1-section9-div4-article6-p1-text1": "Couple",
    "couple-phones": "Nancy · +358 44 293 1626                  Henri · +358 50 370 8847",
    "auto-main1-section9-div4-article6-span1-text1": "Contact only if needed.",
    "auto-main1-section10-div1-p1-text1": "A little sea, a lot of love.",
    "auto-main1-section10-div1-h21-text1": "Keep them present.",
    "auto-main1-section10-div1-h21-text3": "Keep the day moving.",
    "auto-main1-section10-div1-p2-text1": "Clear roles, quiet handovers, full glasses of water (and wine) — and also enjoy the day.",
    "auto-main1-section11-div1-div1-p1-text1": "Honest answers welcome",
    "preferences-title": "Not for me?",
    "preferences-lead": "Please let us know if there are tasks you would genuinely enjoy — and any you would rather not do. We want the jobs to suit everyone, and we are always happy to swap or rethink assignments.",
    "preferences-note": "This is only our first draft of delegating things to everyone, not a fixed list. Message Nancy or Henri; no explanation is needed and there are no wrong answers.",
    "auto-main1-section11-div1-div1-div1-div2-div1-span1-text1": "",
    "preferences-happy-example": "",
    "auto-main1-section11-div1-div1-div1-div2-div1-span2-text1": "",
    "preferences-reassign-example": "",
    "auto-footer1-div1-strong1-text1": "Nancy & Henri · 19.09.2026",
    "auto-footer1-div1-span1-text1": "Draft squad plan · Updated",
    "auto-footer1-p1-text1": "Transport and venue facts checked against official HSL and Suomenlinna guidance. Reconfirm all live schedules and supplier timings."
  }
};
